### PR TITLE
Update to Blacklight 6

### PR DESCRIPTION
**Pull request by eliotjordan**
- Updates to blacklight version 6. 
- Removes custom autocomplete and uses blacklight autocomplete instead.

### CODE REVIEW

**Comment by eliotjordan** [comment]
@tampakis (or whoever want to take a look), when you have a chance.

**Comment by escowles** [comment]
This looks good to me.  The only thing I noticed was a couple of deprecation warnings in the test output: https://travis-ci.org/pulibrary/pulmap/builds/147552589#L449

It would be good to clean those up as part of this PR if it's easy to do (or make a ticket to do it later).

**Comment by eliotjordan** [comment]
Thanks, @escowles I'll make a PR in Geoblacklight addressing those.  https://github.com/geoblacklight/geoblacklight/issues/435

**Comment by escowles** [comment]
👍

**Pull request merged**
