### PR TITLE
Add logo. Closes #51

### LINKED ISSUE #51: Logo
Create real logo for LIME. Perhaps this can wait until the name is 100% approved.

### PR DESCRIPTION
**Pull request by axamei**

### CODE REVIEW

**Comment by eliotjordan** [comment]
@jpstroop @tampakis What do you think? Good logo to start out with?

**Comment by tampakis** [comment]
Personally I prefer the font which had lower case letters, but for sure this is much better than the "geoblacklight" logo.

**Comment by eliotjordan** [comment]
@tampakis I agree. I think the mixed upper and lower text looks better.

**Comment by axamei** [comment]
I'll change to sans-serif with title case.

**Pull request merged**
