### PR TITLE
Update restricted lock-icon color to red & updates title

### PR DESCRIPTION
**Pull request by christinach**
Screen Shot 2019-07-02 at 9 27 12 AM

`Show page`
Screen Shot 2019-07-02 at 9 31 04 AM

### CODE REVIEW

**Comment by christinach** [comment]
I think the red makes it more obvious. I didn't change the size.

**Comment by christinach** [comment]
Should we update the title to be `Campus only` vs `Restricted`?

**Comment by escowles** [comment]
You have to login to access the restricted items, right? Maybe we should change the title to "Princeton Only"?

I agree the red is very visible — maybe we could make it orange instead, which goes nicely with Princeton Only?

**Comment by christinach** [comment]
I remember @eliotjordan mentioning that you have to contact the map-department to request to see the map in person. 
I will change the color to the pul orange.

**Comment by christinach** [comment]
@escowles  I'll change the title to 'Princeton Only'

**Comment by christinach** [comment]
Screen Shot 2019-07-02 at 11 15 43 AM

**Pull request merged**
