### PR TITLE
Blacklight::Exceptions::RecordNotFound to redirect to 404 page and not raise an exception

### LINKED ISSUE #880: Blacklight::Exceptions::RecordNotFound should not error, it should show a 404 page, and not raise an exception.
## Backtrace

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/54400/faults/67218719)

### PR DESCRIPTION
**Pull request by christinach**
closes #880

### CODE REVIEW

**Comment by christinach** [comment]
@eliotjordan do we want the 404 page from public to look prettier or is it ok as it is?

**Review by eliotjordan — CHANGES_REQUESTED** [review]
This doesn't return a 404 status code. It should work with a `status: 404` param. Or maybe render the 404 page with the correct status instead of redirecting? 
```
render file: "#{Rails.root}/public/404.html", layout: false, status: 404
```

From [SO](https://stackoverflow.com/questions/2385799/how-to-redirect-to-a-404-in-rails).

**Comment by christinach** [comment]
Thank you @eliotjordan . I fixed the 404. Another question is more about the layout. If we use the layout then it looks like:

Screen Shot 2021-05-04 at 7 06 48 AM
and the Library logo positions with some offset in the navbar.


If the layout is false then it looks like:
Screen Shot 2021-05-04 at 7 07 01 AM


I'm in favor of using the layout (1st screenshot). What do you think?

**Comment by eliotjordan** [comment]
@christinach Looks better with the layout.

**Comment by christinach** [comment]
Ok I'll put it in!

**Comment by christinach** [comment]
https://maps-staging.princeton.edu/catalog/stanford-th998sw3451notreal

**Review by eliotjordan — APPROVED** [review]

**Pull request merged**
