### PR TITLE
add search typeahead

### PR DESCRIPTION
**Pull request by eliotjordan**
Adds autocomplete/typeahead functionality. Cribbed almost entirely from @mejackreed's excellent commits in [Earthworks](https://github.com/sul-dlss/earthworks/pull/241).

### CODE REVIEW

**Comment by mejackreed** [comment]
:shipit: :smile:

**Comment by tampakis** [comment]
Looks cool! @mejackreed's typeahead code might find itself into our other Blacklight projects soon.

**Comment by mejackreed** [comment]
@tampakis I would like to pull it into a Blacklight plugin... what do you think?

**Comment by eliotjordan** [comment]
:+1: for blacklight plugin.

**Comment by tampakis** [comment]
@mejackreed that would be a great idea, I think a lot of people would use it

**Pull request merged**
