### PR TITLE
initial home page topic cards

### PR DESCRIPTION
**Pull request by eliotjordan**
Adds three initial topics Sanborn Maps, Geospatial Data, and Scanned Maps. Advances #53.

### CODE REVIEW

**Comment by eliotjordan** [comment]
@axapu Not sure if I made the cards linkable in the best way. Also, wondering about other icons. I tried substituting some geoblacklight icon fonts, but they didn't align properly. Also, the selection is a bit limited. Ideas?

**Comment by axapu** [comment]
It's hard to know what to click with this implementation. We can add some styles to make sure the cursor indicates that the list items are clickable.

**Comment by eliotjordan** [comment]
@axapu That's a good idea. I wasn't sure the best way to indicate that they were clickable.

**Comment by eliotjordan** [comment]
That looks great. OK to merge, or do you have more to add?

**Comment by axapu** [comment]
Merge away.

**Pull request merged**
