### PR TITLE
Shrink footer

### PR DESCRIPTION
**Pull request by axapu**
Do we need more than the PU logo and the Trustees copyright info?

### CODE REVIEW

**Comment by eliotjordan** [comment]
If we need more, we can add it in on request. Now we need to add some content!

**Comment by eliotjordan** [comment]
Something about that change threw off the formatting on the search bar.

screenshot 2015-11-03 14 22 28

**Comment by axapu** [comment]
Made adjustments. Should be better now.

**Comment by eliotjordan** [comment]
That did it. :+1:

**Pull request merged**
