### PR TITLE
combined featured raster and vector data into geospatial data

### LINKED ISSUE #1039: Collapse "Vector" and "Raster" categories on front page into "GeoSpatial Data"

### PR DESCRIPTION
**Pull request by XanderGardner**
closes #1039

### CODE REVIEW

**Comment by XanderGardner** [comment]
Screen Shot 2022-04-04 at 11 49 02 AM
 I'm open to any ideas for a different description of Geospatial data. It seems a little unusual with Geospatial data being right next to Scanned Maps (which also seems like it would fall under the category of Geospatial data).

**Comment by eliotjordan** [comment]
New Text: 

```
Geospatial Data: Resources for use in GIS Software, including geographic features, aerial photographs, census data, land-use maps, and elevation.
```

**Comment by XanderGardner** [comment]
Screen Shot 2022-04-11 at 10 16 59 AM

**Comment by XanderGardner** [comment]
Screen Shot 2022-04-11 at 11 04 01 AM

**Comment by hackartisan** [comment]
I tried another layout here, which reflects my recollection of a discussion we had ages ago in standup.

Screen Shot 2023-01-12 at 12 08 40 PM

**Review by eliotjordan — APPROVED** [review]
This looks great! 💯

**Pull request merged**
