### PR TITLE
Add GithubAction to run bundle update weekly

### LINKED ISSUE #1121: Update dependencies weekly
Use GitHub Action to run bundle update weekly and create a PR.

### PR DESCRIPTION
**Pull request by eliotjordan**
- Tested locally using [act](https://github.com/nektos/act). Job steps completed successfully, though it didn't have permission to create a PR.
- Created a fine-grained access token for DLS repos and saved it as a secret in the Pulmap repo.
  - https://github.com/organizations/pulibrary/settings/personal-access-tokens/active
  - https://github.com/pulibrary/pulmap/settings/secrets/actions

Closes #1121

### CODE REVIEW

**Review by hackartisan — DISMISSED** [review]
The token will expire in a year. Can you document the permissions you created it with so we can replicate when we have to regenerate?

**Comment by hackartisan** [comment]
I see the permissions when I view the token -- will those still be viewable once it's expired?

**Comment by eliotjordan** [comment]
@hackartisan I think its premature to document the permissions just yet. I want to make sure this action works and then then pare them down to the minimal required. I ticked a number that seem relevant, but I doubt they'll all be needed.

I'm not sure if the permissions will be visible once it's expired.

**Comment by eliotjordan** [comment]
Here's the GitHub documentation on how to create a fine-grained access token (used to give actions permissions to create a full PR on the repo). The current token will expire 10/20/2023, which is the maximum time the token can live.

https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token#creating-a-fine-grained-personal-access-token

Details on the token settings when it comes time to replace it:
Screen Shot 2022-10-20 at 2 49 41 PM

**Pull request merged**
