### PR TITLE
Updates navbar scss - search form &  search form index

### LINKED ISSUE #731: update navbar in mobile view
childe of #722

### PR DESCRIPTION
**Pull request by christinach**
updates navbar scss
updates search form index
updates search form

closes #731

### CODE REVIEW

**Comment by christinach** [comment]
tested using 
Screen Shot 2019-06-25 at 7 50 00 PM

navbar & search input form:
Screen Shot 2019-06-25 at 7 47 22 PM
Screen Shot 2019-06-25 at 7 47 09 PM

**Comment by christinach** [comment]
I need to update the PR for 
Screen Size4.0 in - 2.0 x 3.5 in

**Comment by christinach** [comment]
Update: the previous screens look ok in the mobile view. I was testing using 'browserstack' and it doesn't seem to work well. @axamei suggested to use xcode and the chrome dev tools. The xcode simulator for these screens looks good.

**Comment by christinach** [comment]
@axamei also suggested to use lib-analytics to check which are the common screens/resolutions that users use when they visit pulmap.

**Comment by christinach** [comment]
closes #596
closes #733
closes #731
closes #722

**Comment by christinach** [comment]
In the index navbar between 990 and 1095 pixels the pul__logo wraps. This is something that I should fix.

**Comment by eliotjordan** [comment]
This looks good. One issue I found using the IOS simulator is that the navbar styling is off when viewing with an IPad.

Simulator Screen Shot - iPad (5th generation) - 2019-06-27 at 09 23 15

**Comment by christinach** [comment]
thanks @eliotjordan this is relevant to the resolution range I mentioned.

**Pull request merged**
